/*
 * generated by Xtext
 */
package hu.elte.txtuml.xtxtuml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XtxtUMLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return hu.elte.txtuml.xtxtuml.ui.internal.XtxtUMLActivator.getInstance().getInjector("hu.elte.txtuml.xtxtuml.XtxtUML");
	}
	
}
