/*
 * generated by Xtext
 */
package hu.elte.txtuml.xtxtuml.ui.contentassist

import hu.elte.txtuml.xtxtuml.ui.contentassist.AbstractXtxtUMLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XtxtUMLProposalProvider extends AbstractXtxtUMLProposalProvider {
}
