package hu.elte.txtuml.validation.problems;

public enum ValidationErrorCatalog {

	INVALID_CHILDREN_ELEMENT,
	
	INVALID_MODEL_CLASS_ELEMENT, INVALID_MODIFIER, INVALID_SIGNAL_CONTENT,

	INVALID_TEMPLATE, INVALID_TYPE_WITH_CLASS_ALLOWED, INVALID_TYPE_WITH_CLASS_NOT_ALLOWED, 
	
	WRONG_COMPOSITION_ENDS, WRONG_NUMBER_OF_ASSOCIATION_ENDS, WRONG_TYPE_IN_ASSOCIATION
	
}
