/*
 * generated by Xtext 2.10.0
 */
package hu.elte.txtuml.xd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XDiagramDefinitionStandaloneSetup extends XDiagramDefinitionStandaloneSetupGenerated {

	def static void doSetup() {
		new XDiagramDefinitionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
