/*
 * generated by Xtext 2.10.0
 */
package hu.elte.txtuml.xd.validation

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XDiagramDefinitionValidator extends XDiagramDiamondValidator {
	
}
