/*
 * generated by Xtext
 */
package hu.elte.txtuml.xtxtuml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.elte.txtuml.xtxtuml.ui.internal.XtxtUMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XtxtUMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtxtUMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtxtUMLActivator.getInstance().getInjector(XtxtUMLActivator.HU_ELTE_TXTUML_XTXTUML_XTXTUML);
	}
	
}
