/*
 * generated by Xtext
 */
package hu.elte.txtuml.xtxtuml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.elte.txtuml.xtxtuml.services.XtxtUMLGrammarAccess;

public class XtxtUMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XtxtUMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.elte.txtuml.xtxtuml.parser.antlr.internal.InternalXtxtUMLParser createParser(XtextTokenStream stream) {
		return new hu.elte.txtuml.xtxtuml.parser.antlr.internal.InternalXtxtUMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TUFile";
	}
	
	public XtxtUMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XtxtUMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
