/*
 * generated by Xtext 2.10.0
 */
package hu.elte.txtuml.xd.ui.labeling

import com.google.inject.Inject
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider
import hu.elte.txtuml.xd.xDiagramDefinition.XDInstruction
import org.eclipse.xtext.xtype.XImportSection
import hu.elte.txtuml.xd.xDiagramDefinition.XDDiagram
import hu.elte.txtuml.xd.xDiagramDefinition.XDGroupInstruction
import hu.elte.txtuml.xd.xDiagramDefinition.XDPhantomInstruction

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
class XDiagramDefinitionLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	new(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	def text(XDDiagram element){
		return element.diagramType + " " + element.name;
	}
	
	def text(XDGroupInstruction element){
		return element.op + " " + element.name;
	}
	
	def text(XDPhantomInstruction element){
		return element.op + " " + element.name;
	}
	
	def text(XDInstruction element){
		return 'instruction';
	}
	
	def text(XImportSection element){
		return 'import section';
	}

// Labels and icons can be computed like this:
	
//	def text(Greeting ele) {
//		'A greeting to ' + ele.name
//	}
//
//	def image(Greeting ele) {
//		'Greeting.gif'
//	}
}
