/*
 * generated by Xtext 2.10.0
 */
package hu.elte.txtuml.xd.scoping

import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class XDiagramDefinitionScopeProvider extends AbstractXDiagramDefinitionScopeProvider {
	// SOURCE: http://stackoverflow.com/questions/36224089/xtext-2-9-scope-provider
	
	override getScope(EObject context, EReference reference) {
		super.getScope(context, reference)
	}
	
}
