/*
 * generated by Xtext
 */
package hu.elte.txtuml.xtxtuml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import hu.elte.txtuml.xtxtuml.ui.highlighting.XtxtUMLHighlightingCalculator;

public class XtxtUMLUiModule extends hu.elte.txtuml.xtxtuml.ui.AbstractXtxtUMLUiModule {
	
    public XtxtUMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
    
    @Override
    public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
        return XtxtUMLHighlightingCalculator.class;
    }
    
}
